name: Verilog CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  rtl-check:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Repository Structure
        run: |
          echo "Mini RISC Processor Repository"
          ls -R

      - name: Check RTL Source Files
        run: |
          test -f sim/alu.v
          test -f sim/clock_divider.v
          test -f sim/control_unit.v
          test -f sim/instruction_memory.v
          test -f sim/program_counter.v
          test -f sim/register_file.v
          test -f sim/risc_top.v

      - name: Check Testbench
        run: |
          test -f tb/risc_tb.v

      - name: Check Constraint File
        run: |
          test -f const/risc_basys3.xdc

      - name: Success Message
        run: echo "Mini RISC Processor CI checks passed successfully."